documentation:
  - changed-files:
      - any-glob-to-any-file: "docs/**"

example:
  - changed-files:
      - any-glob-to-any-file:
          - "examples/**"
          - "docs/examples/**"

tests:
  - changed-files:
      - any-glob-to-any-file: "tests/**"
