repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.2
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic>=2,<3.0.0
          - prefect>=3.0
          - langchain_core
          - langchain_anthropic
          - langchain_openai
          - langchain_google_genai
        files: ^(src/controlflow/utilities/types.py)$
